services:
  db:
    container_name: ai-saas-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data

  adminer:
    container_name: ai-saas-adminer
    image: adminer
    ports:
      - 8080:8080
